### ISSUE TITLE
Update Choose Proposal Modal

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo-deprecated#1003]
Add tabs for Basic and Advanced to the proposal modal

**Comment by 7helles** [comment]
Figma link: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=7927%3A207809

Design suggestions:

![Image](https://user-images.githubusercontent.com/97971946/198122930-4a9f1287-6528-45b1-aadd-b989570ba6b5.png)

![Image](https://user-images.githubusercontent.com/97971946/198125094-de880b23-760c-4ed4-b052-cf9aa146087f.png)


Notes:
- One idea had been to combine the two funding request forms into one, and the same for the request tokens/shares forms, but I separated those back out for this version of the designs.
- The tabs are styled exactly like the main nav tab component except that the font size is 18. This should probably become a new component because it's also used in https://github.com/HausDAO/daohaus-monorepo/issues/248.
- I expect the modal shrinking/expanding would be an issue for cumulative layout shift, so the Advanced tab view can remain as tall as the Basics tab with the bottom area empty.

**Comment by earth2travis** [comment]
Order the tabs like the headings below:

## Basic  

- Signal Request  
- DAO Token Request  
- DAO Token Swap  
- ERC-20 Token Transfer  
- Network Token Transfer  

## Advanced  

- Use WalletConnect  
- Update Governance Settings  
- Update Token Settings 
- Update Shaman Settings  
- Add Shaman 
- Remove Member

**Comment by earth2travis** [comment]
@brossetti1 did you see the message above with ordering and which ones need to go on each tab?

We should probably also update the headings and text text (colors, size, spacing) to make the modal contents easier to read. Cc: @0xRowdy

**Comment by earth2travis** [comment]
@brossetti1 it also seems like the DAO Token Request proposal is missing

**Comment by earth2travis** [comment]
The "Start" button should probably read "Create"
